# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker-compose build
#      Start app: docker-compose up app
#       Stop all: docker-compose down
#
version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  app:
    image: linux/amd64:latest
    build:
      context: .
    platform: linux/amd64
    environment:
      <<: *shared_environment
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
    
    # This was added, so the port might not work for some reason
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: sasaCompany
      MONGO_INITDB_ROOT_PASSWORD: Parvardegar1
    ports:
      - 2717:27017
    volumes:
      - mongodb_data_container:/data/db
      
volumes:
  mongodb_data_container:
      

  
